Models/ads.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.IO;
namespace openmarket.Models
{
    public class ads
    {
        public AppDbContext db;
        public ads(AppDbContext _db)
        {
            db = _db;
        }
        public IList<ads> adsList(string page, string format)
        {
            
            return null;
        }
    }
}

Pages/ads/destacar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using System.Text;
using openmarket.Models;

namespace MyApp.Namespace
{
    public class destacarModel : PageModel
    {
        public AppDbContext db;
        [BindProperty(SupportsGet = true)] public int SessionUser { get; set; } = 0;
        [BindProperty] public int Cookies { get; set; }
        public IHttpContextAccessor accessor { get; set; }
        public destacarModel(AppDbContext _db, IHttpContextAccessor _accessor)
        {
            db = _db;
            accessor = _accessor;
        }
        [BindProperty] public string Title { get; set; }
        public IList<ads_plans> plans;
        [BindProperty] public ads_movs ads_movs { get; set; }
        public IList<alerts> alerts_list;
        [BindProperty(SupportsGet = true)] public int advert_id { get; set; }
        [BindProperty] public string _Msg { get; set; }
        public IActionResult OnGet()
        {
            _Msg = Request.Query["Msg"];
            if (Request.Cookies["Accepted"] != null)
            {
                Cookies = 1;
            }
            else
            {
                Cookies = 0;
            }
            //Sessão do utilizador
            valueFormat formatter = new valueFormat();
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userID")))
            {
                SessionUser = Convert.ToInt32(HttpContext.Session.GetString("userID"));
                if (db.accounts.Where(x => x.id == SessionUser).Select(x => x.status).Single() == 11)
                {
                    HttpContext.Session.Remove("userID");
                    if (Request.Cookies["fzid"] != null)
                    {
                        var cookieOptions = new CookieOptions
                        {
                            Expires = DateTime.Now.AddDays(-1)
                        };
                        Response.Cookies.Append("fzid", "0", cookieOptions);
                    }
                    return Redirect("~/entrar");
                }
            }
            else
            {
                string userCookie = Request.Cookies["fzid"];
                if (userCookie != null)
                {
                    int id = Convert.ToInt32(formatter.decrypter(userCookie));
                    if (db.accounts.Where(x => x.id == id).Count() == 1)
                    {
                        SessionUser = id;
                        HttpContext.Session.SetString("userID", Convert.ToString(SessionUser));
                    }
                    else
                    {
                        return Redirect("~/entrar");
                    }
                }
                else
                {
                    return Redirect("~/entrar");
                }
            }
            if (Request.Cookies["fz_dstc"] == null)
            {
                alerts_list = db.alerts.Where(x => x.page == "destacar" && x.status == 1).ToList();
            }
            advert_id = Convert.ToInt32(Request.Query["anuncio"]);
            if (advert_id > 0)
            {
                if (db.adverts.Where(x => x.id == advert_id).Select(x => x.account).Single() != Convert.ToInt32(SessionUser))
                {
                    return Redirect("~/minha-conta");
                }
                else
                {
                    Title = db.adverts.Where(x => x.id == advert_id).Select(x => x.title).Single();
                    string categoryName = db.adverts.Where(x => x.id == advert_id).Select(x => x.category).First();
                    plans = db.ads_plans.Where(x => x.category == categoryName).ToList();
                    return null;
                }
            }
            else
            {
                return Redirect("~/minha-conta");
            }
        }
        public IActionResult OnPostSubscribe(int id, int plan_id)
        {
            SessionUser = Convert.ToInt32(HttpContext.Session.GetString("userID"));
            if (SessionUser == db.adverts.Where(x => x.id == id).Select(x => x.account).First())
            {
                if (db.ads_movs.Any(x => x.advert == id && x.expiration.Date > DateTime.Now.Date))
                {
                    return Redirect("~/minha-conta?Msg=PlanoDecorrer");
                }
                else
                {
                    int plan_price = db.ads_plans.Where(x => x.id == plan_id).Select(x => x.price).First();
                    int plan_days = db.ads_plans.Where(x => x.id == plan_id).Select(x => x.days_principal).First();
                    int user_wallet = db.accounts.Where(x => x.id == SessionUser).Select(x => x.wallet).First();
                    if (user_wallet >= plan_price)
                    {
                        var newMov = new ads_movs()
                        {
                            plan = plan_id,
                            date = DateTime.Now,
                            advert = id,
                            expiration = DateTime.Now.AddDays(plan_days)
                        };
                        db.ads_movs.Add(newMov);
                        db.SaveChanges();

                        wallet wallet = new wallet(db);
                        wallet.insertPlan(plan_id, SessionUser);
                        return Redirect("~/minha-conta?Msg=NovoPlano");
                    }
                    else
                    {
                        return Redirect("~/ads/destacar?anuncio=" + id + "&Msg=SemPontos");
                    }
                }
            }
            else
            {
                return Redirect("~/minha-conta");
            }
        }
        public IActionResult OnPostLogout()
        {

            HttpContext.Session.Remove("userID");
            if (Request.Cookies["fzid"] != null)
            {
                var cookieOptions = new CookieOptions
                {
                    Expires = DateTime.Now.AddDays(-1)
                };
                Response.Cookies.Append("fzid", "0", cookieOptions);
            }
            return Redirect("~/index");
        }
    }
}

Pages/ads/destacar.cshtml
@page
@model MyApp.Namespace.destacarModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@section head{
    <title>OpenMarket - @Model.Title</title>
    <meta name="title" content="OpenMarket - @Model.Title" />
    <meta name="description" content="Destaca os teus anúncios no OpenMarket e fecha o negócio mais rápido." />
    @* Facebook, Others *@
    <meta property="og:title" content="OpenMarket - @Model.Title">
    <meta property="og:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
    <meta property="og:image:width" content="400" />
    <meta property="og:image:height" content="300" />
    <meta property="og:url" content="https://www.openmarket.com/ads/destacar">
    <meta property="og:type" content="article" />
    <meta property="og:description" content="Destaca os teus anúncios no OpenMarket e fecha o negócio mais rápido.">
                    @* Twitter *@
    <meta property="twitter:title" content="OpenMarket - @Model.Title">
    <meta name="twitter:description" content="Destaca os teus anúncios no OpenMarket e fecha o negócio mais rápido.">
    <meta name="twitter:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
    <meta name="twitter:card" content="summary_large_image">
    <link rel="stylesheet" href="~/css/account.css?v=104" />
    <script async src="~/js/main.js?v=104"></script>
}
@section login{ 
    <div class="navbar-login">
        <a class="login-link" href="~/entrar">My OpenMarket</a>
    </div>
}
<main id="ads-container">
    <div id="ads-options">
        
            @if(@Model.plans.Count() > 0)
            {
                <h2>Destaque o seu anúncio e obtenha melhores resultados!</h2>
        <h3>Escolha o seu plano entre as opções a baixo:</h3>            
        <form method="post" asp-page-handler="Subscribe" asp-route-id="@Model.advert_id" id="ads-plans">
                @foreach (var plan in Model.plans)
                {
                        <div class="plan-option">
                            <img src="" alt="">
                            <h2>@plan.name</h2>
                    @* Principal *@
                    @if (@plan.days_principal > 0)
                    {
                                    <p>Página Principal</p>
                                    <p class="days-on"><b>@plan.days_principal</b> dias</p>
                    }
                    else
                    {
                                    <p>Página Principal</p>
                                    <p class="days-on disabled">Não incluído</p>
                    }
                            <hr>
                    @* Destaque *@
                    @if (@plan.days_featured > 0)
                    {
                                    <p>Em destaque</p>
                                    <p class="days-on"><b>@plan.days_featured</b> dias</p>
                    }
                    else
                    {
                                    <p>Em destaque</p>
                                    <p class="days-on disabled">Não incluído</p>
                    }
                            <hr>
                    @* Sugestões *@
                    @if (@plan.days_top > 0)
                    {
                                    <p>Sugestões</p>
                                    <p class="days-on"><b>@plan.days_top</b> dias</p>
                    }
                    else
                    {
                                    <p>Sugestões</p>
                                    <p class="days-on disabled">Não incluído</p>
                    }
                            <hr>
                            <p>Preço</p>
                            <p><b>@plan.price</b> pontos</p>
                            <hr>
                            <button type="submit" name="plan_id" value="@plan.id">Comprar</button>
                        </div>
                }
            </form>
            }
            else
            {
                <h2>Sem planos disponíveis para o seu anúncio.</h2>
                <h3>Para mais informações contacte a nossa equipa.</h3>
                <a href="~/minha-conta/conversas">Entrar em contacto</a>
            }
            
    </div>
</main>
@if (Model.alerts_list != null)
{
    foreach (var alert in Model.alerts_list)
    {
                <div class="alerts-container">
            <div class="alert-content">
                <span onclick="closePanel('alerts-container');cookieAlert('fz_dstc', '@alert.cookie_time');">&times;</span>
                <h2>@alert.title</h2>
                <textarea id="alert-text" readonly>@alert.text</textarea>
                <script>
                    var textarea = document.getElementById("alert-text");
                    textarea.style.height = textarea.scrollHeight + 20 + "px";
                </script>
                @if (!string.IsNullOrEmpty(@alert.button_text))
                {
                                <a onclick="cookieAlert('fz_dstc', '@alert.cookie_time')" href="@alert.button_url">@alert.button_text</a>
                }
                    </div>
                </div>
    }
}
<div id="alert-message-container" style="display: none;">
    <div class="alert-content">
        <h3 id="alert-message-title">Pontos insuficientes</h3>
        <p id="alert-message-p1">Não dispões de pontos suficientes para adquirir este plano.</p>
        <p id="alert-message-p2">Podes optar por outro plano ou adquirir mais pontos. Para mais informações contacta pelo chat a nossa equipa. </br> <a
                href="~/minha-conta/conversas">Entrar nas Chat</a></p>
        <button type="button"
            onclick="document.getElementById('alert-message-container').style.display = 'none'">Fechar</button>
    </div>
</div>
@if (Model._Msg == "SemPontos")
{
        <script type="text/javascript">
        document.getElementById('alert-message-container').style.display = "flex";
    </script>
}