Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
namespace openmarket.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) :base(options){}
        public DbSet <accounts_ratings> accounts_ratings {get; set;}
        public DbSet <accounts> accounts {get; set;}
        public DbSet <adverts> adverts {get; set;}
        public DbSet <attributes> attributes {get; set;}
        public DbSet <categories_attributes> categories_attributes {get; set;}
        public DbSet <categories> categories {get; set;}
        public DbSet <cities> cities {get; set;}
        public DbSet <conversations> conversations {get; set;}
        public DbSet <countries> countries {get; set;}
        public DbSet <groups> groups {get; set;}
        public DbSet <images> images {get; set;}
        public DbSet <login_logs> login_logs {get; set;}
        public DbSet <marks> marks {get; set;}
        public DbSet <models> models {get; set;}
        public DbSet <municipalities> municipalities {get; set;}
        public DbSet <search_register> search_register {get; set;}
        public DbSet <tables> tables {get; set;}
        public DbSet <users> users {get; set;}
        public DbSet <views> views {get; set;}
        public DbSet <favorites> favorites {get; set;}
        public DbSet <news> news {get; set;}
        public DbSet <month> month {get; set;}
        public DbSet <ads_plans> ads_plans {get; set;}
        public DbSet <wallet_movs> wallet_movs {get; set;}
        public DbSet <wallet_movs_origin> wallet_movs_origin {get; set;}
        public DbSet <ads_movs> ads_movs {get; set;}
        public DbSet <alerts> alerts {get; set;}
    }
}

Models/Charts.cs
using System;
namespace openmarket.Models
{
    public class Charts
    {
        public int valueX { get; set; }
        public int valueY { get; set; }
    }
}

Models/accounts_ratings.cs
using System;
namespace openmarket.Models
{
    public class accounts_ratings
    {
        public int id { get; set; }
        public int account_evaluator { get; set; }
        public int account_rated { get; set; }
        public int value { get; set; }
        public DateTime date { get; set; }
        public int status { get; set; }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using System.Text;
using Microsoft.EntityFrameworkCore;
using openmarket.Models;

namespace openmarket.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty] public AppDbContext db { get; set; }
        public IndexModel(AppDbContext _db)
        {
            db = _db;
        }
        [BindProperty(SupportsGet = true)] public int SessionUser { get; set; } = 0;
        [BindProperty] public byte[] UserPicture { get; set; }
        [BindProperty] public int Cookies { get; set; }
        [BindProperty] public string searchText { get; set; }
        public IList<cities> cities;
        public IList<municipalities> municipalities;
        public IList<groups> groups;
        public IList<_adverts> adverts;
        public IList<alerts> alerts_list;
        public async Task OnGetAsync()
        {
            if (Request.Cookies["accepted"] != null)
            {
                Cookies = 1;
            }
            else
            {
                Cookies = 0;
            }
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userID")))
            {
                SessionUser = Convert.ToInt32(HttpContext.Session.GetString("userID"));
                if (db.accounts.Where(x => x.id == SessionUser).Select(x => x.status).Single() == 11)
                {
                    HttpContext.Session.Remove("userID");
                    if (Request.Cookies["fzid"] != null)
                    {
                        var cookieOptions = new CookieOptions
                        {
                            Expires = DateTime.Now.AddDays(-1)
                        };
                        Response.Cookies.Append("fzid", "0", cookieOptions);
                    }
                }
            }
            else
            {
                valueFormat formatter = new valueFormat();
                string userCookie = Request.Cookies["fzid"];
                if (userCookie != null)
                {
                    int id = Convert.ToInt32(formatter.decrypter(userCookie));
                    if (db.accounts.Where(x => x.id == id).Count() == 1)
                    {
                        SessionUser = id;
                        HttpContext.Session.SetString("userID", Convert.ToString(SessionUser));
                    }
                }
            }

            cities = await db.cities.OrderBy(x => x.name).ToListAsync();
            municipalities = await db.municipalities.OrderBy(x => x.name).ToListAsync();
            groups = await db.groups.OrderBy(x => x.id).ToListAsync();
            _adverts_return advertsList = new _adverts_return(db);
            adverts = advertsList.principal_adverts(null, null);
            if (Request.Cookies["fz_idx"] == null)
                {
                    alerts_list = db.alerts.Where(x => x.page == "index" && x.status == 1).ToList();
                }
        }
        public IActionResult OnGetAnuncios(string type, string location)
        {
            _adverts_return advertsList = new _adverts_return(db);
            adverts = advertsList.principal_adverts(type, location);
            return new JsonResult(adverts);
        }
        public IActionResult OnGetSugestoes(string pesquisa, string tipo, string localizacao, string categoria, string sub_categoria)
        {
            IQueryable<_adverts> filter_adverts = from x in db.adverts
                                                  join y in db.images on x.id equals y.product into image
                                                  from y in image.DefaultIfEmpty()
                                                  where x.status == 1
                                                  select new _adverts
                                                  {
                                                      id = x.id,
                                                      title = x.title,
                                                      image_filename = y.filename,
                                                      groupName = x.groupName
                                                  };
            adverts = filter_adverts.ToList();
            if (!string.IsNullOrEmpty(pesquisa) && adverts.Count() > 0)
            {
                var words = pesquisa.Split(" ");
                foreach (var word in words.Where(x => x.Length > 2))
                {
                    adverts = adverts.Where(x => x.title.ToLower().Contains(word.ToLower())).ToList();
                }
            }
            List<string> titles = new List<string>();
            foreach (var item in adverts)
            {
                if (!titles.Contains(item.title))
                {
                    titles.Add(item.title);
                }
            }
            for (int i = 0; i < titles.Count(); i++)
            {
                while (adverts.Where(x => x.title == titles[i]).Count() > 1)
                {
                    var title = adverts.FirstOrDefault(x => x.title == titles[i]);
                    adverts.Remove(title);
                }
            }
            adverts = adverts.Take(5).OrderBy(x => x.title).ToList();
            return new JsonResult(adverts);
        }
        public IActionResult OnGetView(int anuncio, string pagina)
        {
            views views = new views(db);
            views.Register(anuncio, pagina);
            return null;
        }
    }
}

Pages/entrar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using System.Net;
using System.IO;
using System.Text;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using System.Net.Mail;
using openmarket.Models;

namespace MyApp.Namespace
{
    public class entrarModel : PageModel
    {
        public AppDbContext db;
        [BindProperty(SupportsGet = true)] public int SessionUser { get; set; } = 0;
        [BindProperty] public byte[] UserPicture { get; set; }
        [BindProperty] public int Cookies { get; set; }

        public IHttpContextAccessor accessor { get; set; }
        public entrarModel(AppDbContext _db, IHttpContextAccessor _accessor)
        {
            db = _db;
            accessor = _accessor;
        }
        [BindProperty] public string _Msg { get; set; }
        [BindProperty] public accounts accounts { get; set; }
        StreamReader reader;
        [BindProperty(SupportsGet = true)] public string subject { get; set; }
        [BindProperty(SupportsGet = true)] public string body { get; set; }
        [BindProperty(SupportsGet = true)] public string backUrl { get; set; }
        [BindProperty(SupportsGet = true)] public string convite { get; set; }
        [BindProperty(SupportsGet = true)] public bool register { get; set; } = false;
        public IList<alerts> alerts_list;
        valueFormat formatter = new valueFormat();

        public IActionResult OnGet()
        {
            _Msg = Request.Query["Msg"];
            if (Request.Cookies["Accepted"] != null)
            {
                Cookies = 1;
            }
            else
            {
                Cookies = 0;
            }
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userID")))
            {
                SessionUser = Convert.ToInt32(HttpContext.Session.GetString("userID"));
                if (db.accounts.Where(x => x.id == SessionUser).Select(x => x.status).Single() == 11)
                {
                    HttpContext.Session.Remove("userID");
                    if (Request.Cookies["fzid"] != null)
                    {
                        var cookieOptions = new CookieOptions
                        {
                            Expires = DateTime.Now.AddDays(-1)
                        };
                        Response.Cookies.Append("fzid", "0", cookieOptions);
                    }
                    return Redirect("~/entrar");
                }
                else
                {
                    return Redirect("~/minha-conta");
                }
            }
            else if (!string.IsNullOrEmpty(Request.Cookies["fzid"]))
            {
                string userCookie = Request.Cookies["fzid"];
                valueFormat formatter = new valueFormat();
                int id = Convert.ToInt32(formatter.decrypter(userCookie));
                SessionUser = id;
                return Redirect("~/minha-conta");
            }
            if (!string.IsNullOrEmpty(Request.Query["backUrl"]))
            {
                if (!string.IsNullOrEmpty(Request.Query["name"]))
                {
                    backUrl = Request.Query["backUrl"] + "?" + formatter.urlFormat(Request.Query["name"]) + "&id=" + Request.Query["id"];
                }
                else if (!string.IsNullOrEmpty(Request.Query["id"]))
                {
                    backUrl = Request.Query["backUrl"] + "?id=" + Request.Query["id"];
                }
                else
                {
                    backUrl = Request.Query["backUrl"];
                }
            }
            if (!string.IsNullOrEmpty(Request.Query["convite"]))
            {
                convite = Request.Query["convite"];
                register = true;
            }
            if (Request.QueryString.ToString().Contains("?registar"))
            {
                register = true;
            }
            if (Request.Cookies["fz_lg"] == null)
            {
                alerts_list = db.alerts.Where(x => x.page == "entrar" && x.status == 1).ToList();
            }
            return null;
        }
        public IActionResult OnPostLogin(string backUrl)
        {
            if (!string.IsNullOrEmpty(accounts.email) && db.accounts.Where(x => x.email == accounts.email.Trim()).Count() > 0)
            {
                var password = db.accounts.Where(x => x.email == accounts.email.Trim()).Select(x => x.password).FirstOrDefault().ToString();
                if (!string.IsNullOrEmpty(accounts.password) && accounts.password.Trim() == password)
                {
                    string userid = db.accounts.Where(x => x.email == accounts.email.Trim()).Select(x => x.id).First().ToString();
                    int accountStatus = db.accounts.Where(x => x.id == Convert.ToInt32(userid)).Select(x => x.status).Single();
                    if (accountStatus == 11)
                    {
                        return Redirect("entrar?Msg=conta-bloqueada");
                    }
                    else
                    {
                        HttpContext.Session.SetString("userID", userid);
                        var cookieOptions = new CookieOptions
                        {
                            Expires = DateTime.Now.AddDays(30)
                        };
                        Response.Cookies.Append("fzid", formatter.encrypter(userid), cookieOptions);
                        //Registo de sessão
                        newLog(int.Parse(userid));
                        if (!string.IsNullOrEmpty(backUrl))
                        {
                            return Redirect("~/" + backUrl);
                        }
                        else
                        {
                            return Redirect("~/entrar");
                        }
                    }
                }
                else if (!string.IsNullOrEmpty(backUrl))
                {
                    return Redirect("entrar?backUrl=" + backUrl + "&Msg=login-incorrecto");
                }
                else
                {
                    return Redirect("entrar?Msg=login-incorrecto");
                }
            }
            else
            {
                if (!string.IsNullOrEmpty(backUrl))
                {
                    return Redirect("entrar?backUrl=" + backUrl + "&Msg=nao-encontrado");
                }
                else
                {
                    return Redirect("entrar?Msg=nao-encontrado");
                }
            }
        }
        public IActionResult OnPostRegister(string invite, string backUrl)
        {
            wallet wallet = new wallet(db);
            int email_count = db.accounts.Where(x => x.email == accounts.email.Trim()).Count();
            int user_count = db.accounts.Where(x => x.username == accounts.username.Trim()).Count();
            if (email_count > 0)
            {
                return Redirect("~/entrar?registar&Msg=email-registado");
            }
            else if (user_count > 0)
            {
                return Redirect("~/entrar?registar&Msg=nome-utilizador-registado");
            }
            else
            {
                var username = accounts.username.Replace(" ", "");
                var account = new accounts
                {
                    username = formatter.stringFormat(formatter.removeEmojis((accounts.username.Trim()))),
                    email = formatter.stringFormat(formatter.removeEmojis(accounts.email.Trim())),
                    password = accounts.password.Trim(),
                    newsletter = accounts.newsletter,
                    register = DateTime.Now,
                    status = 1
                };
                db.accounts.Add(account);
                db.SaveChanges();
                string userid = db.accounts.Where(x => x.username == account.username).Select(x => x.id).First().ToString();
                HttpContext.Session.SetString("userID", userid);
                var cookieOptions = new CookieOptions
                {
                    Expires = DateTime.Now.AddDays(30)
                };
                Response.Cookies.Append("fzid", formatter.encrypter(userid), cookieOptions);
                wallet.insertMov(6, Convert.ToInt32(userid), 0, true);
                //Email de registo
                SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential("openmarket@gmail.com", "YourPassword");
                smtp.EnableSsl = true;
                MailAddress from = new MailAddress("openmarket@gmail.com", "OpenMarket");
                MailAddress to = new MailAddress(accounts.email);
                MailMessage mailMessage = new MailMessage(from, to);
                mailMessage.Subject = "Registo de conta";
                mailMessage.IsBodyHtml = true;
                reader = new StreamReader("wwwroot/templates/emails/create-account.htm");
                body = reader.ReadToEnd();
                body = body.Replace("{username}", username);
                mailMessage.Body = body;
                smtp.Send(mailMessage);
                //Mensagem para o utilizador
                string message = "Bem-vindo ao OpenMarket, o teu site de classificados onde podes vender ou comprar praticamente tudo. Caso tenhas alguma questão poderás usar esta conversa para comunicar com a nossa equipa. Obrigado pela preferência, a equipa do OpenMarket!";
                var newPost = new conversations
                {
                    sender = 1,
                    receiver = Convert.ToInt32(userid),
                    message = message,
                    date = DateTime.Now,
                    status = "Por ler"
                };
                db.conversations.Add(newPost);
                db.SaveChanges();

Pages/admin/accounts.cshtml
@page
@model MyApp.Namespace.accountsModel
@{
    <title>Utilizadores</title>
    Layout = "~/Pages/Shared/_LayoutAdmin.cshtml";
    <link rel="stylesheet" href="~/css/admin.css?v=104" />
    <script async defer src="~/js/admin.js?v=104"></script>
}
<section class="navbar navbar-left">
   <partial name="_AdminMenu"/>
</section>
<section id="accounts-container">
    <form method="POST" asp-page-handler="Search" class="search-content">
        <input type="text" name="searchText" class="search-text" placeholder="Procurar...">
        <button class="search-button" type="submit"><img src="/imgs/search.png" title="Procurar utilizador"
                alt="Search"></button>
    </form>
    @if (Model.accounts.Count > 0)
    {
        <table class="accounts-content">
            <thead>
                <tr class="account-row">
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Cidade</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.accounts)
                {
                    <tr class="account-row">
                        <td>@item.username</td>
                        <td>@Html.DisplayFor(x => item.email)</td>
                        @if (!string.IsNullOrEmpty(item.city))
                        {
                            <td>@Html.DisplayFor(x => item.city)</td>
                        }
                        else
                        {
                            <td></td>
                        }
                        @{
                            var url = "/admin/adverts?user=" + @item.username.Replace(" ", "");
                            <td>
                                <a href="@url"><img src="/imgs/view.png" title="Ver anúncios" alt="Ver anúncio"></a>
                                <a asp-page="edit-account" asp-route-id="@item.id"><img src="/imgs/edit.png" title="Editar conta"
                                alt="Editar conta"></a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h2>Sem contas de utilizador para apresentar!</h2>
    }
    <form method="POST" class="pagination">
        @if (Model.TotalPages < 6)
        {
            @for (var i = 1; i <= Model.TotalPages; i++)
            {
                <li onclick="pagination('@i')" class="page-item @(i == Model.currentpage ? " active": "" )">
                    <a name="pagination" class="page-link">@i</a>
                </li>
            }
        }
        else if (Model.TotalPages > 5 && Model.currentpage > 3)
        {
            if (Model.currentpage <= Model.TotalPages - 2)
            {
                @for (var i = @Model.currentpage - 2; i <= @Model.currentpage + 2; i++)
                {
                    <li onclick="pagination('@i')" class="page-item @(i == Model.currentpage ? " active": "" )">
                        <a name="pagination" class="page-link">@i</a>
                    </li>
                }
            }
            else
            {
                if (Model.currentpage == Model.TotalPages - 1)
                {
                    @for (var i = @Model.currentpage - 3; i <= @Model.TotalPages; i++)
                    {
                        <li onclick="pagination('@i')" class="page-item @(i == Model.currentpage ? " active": "" )">
                            <a name="pagination" class="page-link">@i</a>
                        </li>
                    }
                }

                else if (Model.currentpage == Model.TotalPages)
                {
                    @for (var i = @Model.currentpage - 4; i <= @Model.TotalPages; i++)
                    {
                        <li onclick="pagination('@i')" class="page-item @(i == Model.currentpage ? " active": "" )">
                            <a name="pagination" class="page-link">@i</a>
                        </li>
                    }
                }
            }
        }
        else if (Model.TotalPages > 5 && Model.currentpage < 4)
        {
            @for (var i = 1; i <= 5; i++)
            {
                <li onclick="pagination('@i')" class="page-item @(i == Model.currentpage ? " active": "" )">
                    <a name="pagination" class="page-link">@i</a>
                </li>
            }
        }
    </form>
</section>

Pages/admin/dashboard.cshtml
@page
@model MyApp.Namespace.dashboardModel
@{
    <title>Dashboard</title>
    <link rel="stylesheet" href="~/css/admin.css?v=104" />
    Layout = "~/Pages/Shared/_LayoutAdmin.cshtml";
    <script async src="~/js/admin.js?v=104"></script>
    <script async src="~/js/social.js?v=104"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
}
<section class="navbar navbar-left">
    <partial name="_AdminMenu" />
</section>
<section class="dashboard-container">
    <div class="navbar navbar-right">
        <form method="POST" class="control-panel">
            <button class="sitemap" type="submit" asp-page-handler="Sitemap">Sitemap</button>
            <button class="anuncios" type="submit" asp-page-handler="Anuncios">Anuncios</button>
            <button id="Facebook" type="submit" asp-page-handler="Facebook" type="button">Facebook</button>
        </form>
    </div>
    <div id="resume-panel">
        <h4>Resumo de anúncios</h4>
        <p>Pendentes: @Model.adverts_pending</p>
        <p>Atualizados: @Model.adverts_update</p>
    </div>
    <div class="charts">
        <select id="month" class="filter-select" onchange="refreshCharts()">
            @foreach (var item in Model.month_list)
            {
                if (item.id == Model.Month)
                {
                            <option selected value="@item.id">@item.name</option>
                }
                else
                {
                            <option value="@item.id">@item.name</option>
                }
            }
        </select>
        <h2>Visualizações (@Model.views.Sum(x => x.valueY))</h2>
        <canvas id="views_chart" class="charts_content"></canvas>
        <script>
            var xValues = [];
            var yValues = [];
            @foreach (var item in Model.views.OrderBy(x => x.valueX))
            {
                @:yValues.push("@item.valueY");
                DateTime date = new DateTime(DateTime.Now.Year, 1, 1).AddDays(item.valueX - 1);
                string date_string = date.ToString("dd/MM");
                @:xValues.push("@date_string");
            }
                new Chart("views_chart", {
                    type: "line",
                    data: {
                        labels: xValues,
                        datasets: [{
                            fill: false,
                            lineTension: 0,
                            backgroundColor: "rgba(0,0,255,1.0)",
                            borderColor: "rgba(0,0,255,0.1)",
                            data: yValues
                        }]
                    },
                    options: {
                        legend: { display: false },
                        scales: {
                            yAxes: [{ ticks: { min: 0, max: @Model.views.OrderByDescending(x => x.valueY).Select(x => x.valueY).Take(1).SingleOrDefault() + 10 } }],
                        }
                    }
                });
        </script>
    </div>
    @if (Model.Permission == 1)
    {
            <div class="charts">
                <h2>Anúncios (@Model.adverts.Sum(x => x.valueY))</h2>
                <canvas id="adverts_chart" class="charts_content"></canvas>
                <script>
                    var xValues = [];
                    var yValues = [];
                @foreach (var item in Model.adverts.OrderBy(x => x.valueX))
                {
                    @:yValues.push("@item.valueY");
                    DateTime date = new DateTime(DateTime.Now.Year, 1, 1).AddDays(item.valueX - 1);
                    string date_string = date.ToString("dd/MM");
                    @:xValues.push("@date_string");
                }
                        new Chart("adverts_chart", {
                            type: "line",
                            data: {
                                labels: xValues,
                                datasets: [{
                                    fill: false,
                                    lineTension: 0,
                                    backgroundColor: "rgba(0,0,255,1.0)",
                                    borderColor: "rgba(0,0,255,0.1)",
                                    data: yValues
                                }]
                            },
                            options: {
                                legend: { display: false },
                                scales: {
                                    yAxes: [{ ticks: { min: 0, max: @Model.adverts.OrderByDescending(x => x.valueY).Select(x => x.valueY).Take(1).SingleOrDefault() + 5 } }],
                                }
                            }
                        });
                </script>
            </div>
            <div class="charts">
                <h2>Registo de utilizadores (@Model.users.Sum(x => x.valueY))</h2>
                <canvas id="users_chart" class="charts_content"></canvas>
                <script>
                    var xValues = [];
                    var yValues = [];
                @foreach (var item in Model.users.OrderBy(x => x.valueX))
                {
                    @:yValues.push("@item.valueY");
                    DateTime date = new DateTime(DateTime.Now.Year, 1, 1).AddDays(item.valueX - 1);
                    string date_string = date.ToString("dd/MM");
                    @:xValues.push("@date_string");
                }
                        new Chart("users_chart", {
                            type: "line",
                            data: {
                                labels: xValues,
                                datasets: [{
                                    fill: false,
                                    lineTension: 0,
                                    backgroundColor: "rgba(0,0,255,1.0)",
                                    borderColor: "rgba(0,0,255,0.1)",
                                    data: yValues
                                }]
                            },
                            options: {
                                legend: { display: false },
                                scales: {
                                    yAxes: [{ ticks: { min: 0, max: @Model.users.OrderByDescending(x => x.valueY).Select(x => x.valueY).Take(1).SingleOrDefault() + 5 } }],
                                }
                            }
                        });
                </script>
            </div>
            <div id="views-today" class="views-list">
                <h3>Lista de anúncios mais vistos hoje</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Anúncio</th>
                            <th>Visualizações</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if (Model.Views_today.Count > 0)
                    {
                        @foreach (var item in Model.Views_today)
                        {
                                        <tr class="advert-row">
                                            <td>@Html.DisplayFor(x => item.title)</td>
                                            <td>@Html.DisplayFor(x => item.views)</td>
                                        </tr>
                        }
                    }
                    else
                    {
                                <h2>Sem visualizações hoje</h2>
                    }
                    </tbody>
                </table>
            </div>
            <div id="views-week" class="views-list">
                <h3>Lista de anúncios mais esta semana</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Anúncio</th>
                            <th>Visualizações</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if (Model.Views_week.Count > 0)
                    {
                        @foreach (var item in Model.Views_week)
                        {
                                        <tr class="advert-row">
                                            <td>@Html.DisplayFor(x => item.title)</td>
                                            <td>@Html.DisplayFor(x => item.views)</td>
                                        </tr>
                        }
                    }
                    else
                    {
                                <h2>Sem visualizações hoje</h2>
                    }
                    </tbody>
                </table>
            </div>
    }
</section>

Pages/admin/login.cshtml
@page
@model MyApp.Namespace.loginModel
@{
    <title>Admin - Login</title>
    Layout = "~/Pages/Shared/_LayoutAdmin.cshtml";
    <link rel="stylesheet" href="~/css/admin.css?v=104" />
}
<form method="POST" asp-page-handler="login" class="login-admin">
    <p>admin</p>
    <input type="email" asp-for="users.email" placeholder="Email">
    <input type="password" asp-for="users.password" placeholder="Password">
    <button type="submit">Entrar</button>
</form>

@if(Model.Msg != null)
{
    <script type="text/javascript">    
        alert("@Model.Msg");   
    </script> 
}