Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace openmarket.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/contacte-nos.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using System.Net;
using System.Net.Mail;
using System.IO;
using openmarket.Models;

namespace MyApp.Namespace
{
    public class contacte_nosModel : PageModel
    {
        [BindProperty(SupportsGet = true)] public int SessionUser { get; set; } = 0;
        [BindProperty] public int Cookies { get; set; }
        [BindProperty] public string From { get; set; }
        [BindProperty] public string Name { get; set; }
        [BindProperty] public string Subject { get; set; }
        [BindProperty(SupportsGet = true)] public string Body { get; set; }
        [BindProperty(SupportsGet = true)] public int advert_id { get; set; } = 0;
        [BindProperty] public _adverts advert { get; set; }
        [BindProperty(SupportsGet = true)] public string subject { get; set; }
        public IList<alerts> alerts_list;
        StreamReader reader;
        string body = string.Empty;
        public AppDbContext db { get; set; }
        public contacte_nosModel(AppDbContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            if (Request.Cookies["Accepted"] != null)
            {
                Cookies = 1;
            }
            else
            {
                Cookies = 0;
            }
            //Sessão do utilizador
            valueFormat formatter = new valueFormat();
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userID")))
            {
                SessionUser = Convert.ToInt32(HttpContext.Session.GetString("userID"));
                if (db.accounts.Where(x => x.id == SessionUser).Select(x => x.status).Single() == 11)
                {
                    HttpContext.Session.Remove("userID");
                    if (Request.Cookies["fzid"] != null)
                    {
                        var cookieOptions = new CookieOptions
                        {
                            Expires = DateTime.Now.AddDays(-1)
                        };
                        Response.Cookies.Append("fzid", "0", cookieOptions);
                    }
                }
            }
            else
            {
                string userCookie = Request.Cookies["fzid"];
                if (userCookie != null)
                {
                    int id = Convert.ToInt32(formatter.decrypter(userCookie));
                    if (db.accounts.Where(x => x.id == id).Count() == 1)
                    {
                        SessionUser = id;
                        HttpContext.Session.SetString("userID", Convert.ToString(SessionUser));
                    }
                }
            }
            advert_id = Convert.ToInt32(Request.Query["anuncio"]);
            subject = Request.Query["assunto"];
            if (advert_id > 0)
            {
                IQueryable<_adverts> filter = from x in db.adverts
                                              join y in db.images on x.id equals y.product into image
                                              from y in image.DefaultIfEmpty()
                                              where x.status == 1 && x.id == advert_id
                                              select new _adverts
                                              {
                                                  id = x.id,
                                                  title = x.title,
                                                  price = x.price,
                                                  date = x.date,
                                                  municipality = x.municipality,
                                                  city = x.city,
                                                  image_filename = (from r in db.images where r.product == x.id select r).First().filename,
                                                  groupName = x.groupName,
                                                  price_min = x.price_min,
                                                  price_max = x.price_max,
                                                  orc = x.orc
                                              };
                advert = filter.First();
            }
            if (Request.Cookies["fz_ctc"] == null)
            {
                alerts_list = db.alerts.Where(x => x.page == "contacte-nos" && x.status == 1).ToList();
            }
        }

        public IActionResult OnPostSend(string user_email, string Name)
        {
            SessionUser = Convert.ToInt32(HttpContext.Session.GetString("userID"));
            SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new NetworkCredential("openmarket@gmail.com", "YourPassword");
            smtp.EnableSsl = true;
            MailAddress from = new MailAddress(user_email.Trim());
            MailAddress to = new MailAddress("openmarket@gmail.com");
            MailMessage mailMessage = new MailMessage(from, to);
            mailMessage.Subject = Subject;
            mailMessage.IsBodyHtml = true;
            reader = new StreamReader("wwwroot/templates/emails/contact-us.htm");
            body = reader.ReadToEnd();
            if (SessionUser > 0)
            {
                string username = db.accounts.Where(x => x.id == SessionUser).Select(x => x.username).First();
                body = body.Replace("{name}", username);
                body = body.Replace("{email}", db.accounts.Where(x => x.id == SessionUser).Select(x => x.email).First());
            }
            else
            {
                body = body.Replace("{name}", Name.Trim());
                body = body.Replace("{email}", user_email.Trim());
            }
            body = body.Replace("{subject}", Subject);
            body = body.Replace("{message}", Body.Trim());
            mailMessage.Body = body;
            smtp.Send(mailMessage);
            return RedirectToPage("contacte-nos");
        }
    }
}

Pages/entrar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using System.Net;
using System.IO;
using System.Text;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using System.Net.Mail;
using openmarket.Models;

namespace MyApp.Namespace
{
    public class entrarModel : PageModel
    {
        public AppDbContext db;
        [BindProperty(SupportsGet = true)] public int SessionUser { get; set; } = 0;
        [BindProperty] public byte[] UserPicture { get; set; }
        [BindProperty] public int Cookies { get; set; }

        public IHttpContextAccessor accessor { get; set; }
        public entrarModel(AppDbContext _db, IHttpContextAccessor _accessor)
        {
            db = _db;
            accessor = _accessor;
        }
        [BindProperty] public string _Msg { get; set; }
        [BindProperty] public accounts accounts { get; set; }
        StreamReader reader;
        [BindProperty(SupportsGet = true)] public string subject { get; set; }
        [BindProperty(SupportsGet = true)] public string body { get; set; }
        [BindProperty(SupportsGet = true)] public string backUrl { get; set; }
        [BindProperty(SupportsGet = true)] public string convite { get; set; }
        [BindProperty(SupportsGet = true)] public bool register { get; set; } = false;
        public IList<alerts> alerts_list;
        valueFormat formatter = new valueFormat();

        public IActionResult OnGet()
        {
            _Msg = Request.Query["Msg"];
            if (Request.Cookies["Accepted"] != null)
            {
                Cookies = 1;
            }
            else
            {
                Cookies = 0;
            }
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userID")))
            {
                SessionUser = Convert.ToInt32(HttpContext.Session.GetString("userID"));
                if (db.accounts.Where(x => x.id == SessionUser).Select(x => x.status).Single() == 11)
                {
                    HttpContext.Session.Remove("userID");
                    if (Request.Cookies["fzid"] != null)
                    {
                        var cookieOptions = new CookieOptions
                        {
                            Expires = DateTime.Now.AddDays(-1)
                        };
                        Response.Cookies.Append("fzid", "0", cookieOptions);
                    }
                    return Redirect("~/entrar");
                }
                else
                {
                    return Redirect("~/minha-conta");
                }
            }
            else if (!string.IsNullOrEmpty(Request.Cookies["fzid"]))
            {
                string userCookie = Request.Cookies["fzid"];
                valueFormat formatter = new valueFormat();
                int id = Convert.ToInt32(formatter.decrypter(userCookie));
                SessionUser = id;
                return Redirect("~/minha-conta");
            }
            if (!string.IsNullOrEmpty(Request.Query["backUrl"]))
            {
                if (!string.IsNullOrEmpty(Request.Query["name"]))
                {
                    backUrl = Request.Query["backUrl"] + "?" + formatter.urlFormat(Request.Query["name"]) + "&id=" + Request.Query["id"];
                }
                else if (!string.IsNullOrEmpty(Request.Query["id"]))
                {
                    backUrl = Request.Query["backUrl"] + "?id=" + Request.Query["id"];
                }
                else
                {
                    backUrl = Request.Query["backUrl"];
                }
            }
            if (!string.IsNullOrEmpty(Request.Query["convite"]))
            {
                convite = Request.Query["convite"];
                register = true;
            }
            if (Request.QueryString.ToString().Contains("?registar"))
            {
                register = true;
            }
            if (Request.Cookies["fz_lg"] == null)
            {
                alerts_list = db.alerts.Where(x => x.page == "entrar" && x.status == 1).ToList();
            }
            return null;
        }
        public IActionResult OnPostLogin(string backUrl)
        {
            if (!string.IsNullOrEmpty(accounts.email) && db.accounts.Where(x => x.email == accounts.email.Trim()).Count() > 0)
            {
                var password = db.accounts.Where(x => x.email == accounts.email.Trim()).Select(x => x.password).FirstOrDefault().ToString();
                if (!string.IsNullOrEmpty(accounts.password) && accounts.password.Trim() == password)
                {
                    string userid = db.accounts.Where(x => x.email == accounts.email.Trim()).Select(x => x.id).First().ToString();
                    int accountStatus = db.accounts.Where(x => x.id == Convert.ToInt32(userid)).Select(x => x.status).Single();
                    if (accountStatus == 11)
                    {
                        return Redirect("entrar?Msg=conta-bloqueada");
                    }
                    else
                    {
                        HttpContext.Session.SetString("userID", userid);
                        var cookieOptions = new CookieOptions
                        {
                            Expires = DateTime.Now.AddDays(30)
                        };
                        Response.Cookies.Append("fzid", formatter.encrypter(userid), cookieOptions);
                        //Registo de sessão
                        newLog(int.Parse(userid));
                        if (!string.IsNullOrEmpty(backUrl))
                        {
                            return Redirect("~/" + backUrl);
                        }
                        else
                        {
                            return Redirect("~/entrar");
                        }
                    }
                }
                else if (!string.IsNullOrEmpty(backUrl))
                {
                    return Redirect("entrar?backUrl=" + backUrl + "&Msg=login-incorrecto");
                }
                else
                {
                    return Redirect("entrar?Msg=login-incorrecto");
                }
            }
            else
            {
                if (!string.IsNullOrEmpty(backUrl))
                {
                    return Redirect("entrar?backUrl=" + backUrl + "&Msg=nao-encontrado");
                }
                else
                {
                    return Redirect("entrar?Msg=nao-encontrado");
                }
            }
        }
        public IActionResult OnPostRegister(string invite, string backUrl)
        {
            wallet wallet = new wallet(db);
            int email_count = db.accounts.Where(x => x.email == accounts.email.Trim()).Count();
            int user_count = db.accounts.Where(x => x.username == accounts.username.Trim()).Count();
            if (email_count > 0)
            {
                return Redirect("~/entrar?registar&Msg=email-registado");
            }
            else if (user_count > 0)
            {
                return Redirect("~/entrar?registar&Msg=nome-utilizador-registado");
            }
            else
            {
                var username = accounts.username.Replace(" ", "");
                var account = new accounts
                {
                    username = formatter.stringFormat(formatter.removeEmojis((accounts.username.Trim()))),
                    email = formatter.stringFormat(formatter.removeEmojis(accounts.email.Trim())),
                    password = accounts.password.Trim(),
                    newsletter = accounts.newsletter,
                    register = DateTime.Now,
                    status = 1
                };
                db.accounts.Add(account);
                db.SaveChanges();
                string userid = db.accounts.Where(x => x.username == account.username).Select(x => x.id).First().ToString();
                HttpContext.Session.SetString("userID", userid);
                var cookieOptions = new CookieOptions
                {
                    Expires = DateTime.Now.AddDays(30)
                };
                Response.Cookies.Append("fzid", formatter.encrypter(userid), cookieOptions);
                wallet.insertMov(6, Convert.ToInt32(userid), 0, true);
                //Email de registo
                SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential("openmarket@gmail.com", "YourPassword");
                smtp.EnableSsl = true;
                MailAddress from = new MailAddress("openmarket@gmail.com", "OpenMarket");
                MailAddress to = new MailAddress(accounts.email);
                MailMessage mailMessage = new MailMessage(from, to);
                mailMessage.Subject = "Registo de conta";
                mailMessage.IsBodyHtml = true;
                reader = new StreamReader("wwwroot/templates/emails/create-account.htm");
                body = reader.ReadToEnd();
                body = body.Replace("{username}", username);
                mailMessage.Body = body;
                smtp.Send(mailMessage);
                //Mensagem para o utilizador
                string message = "Bem-vindo ao OpenMarket, o teu site de classificados onde podes vender ou comprar praticamente tudo. Caso tenhas alguma questão poderás usar esta conversa para comunicar com a nossa equipa. Obrigado pela preferência, a equipa do OpenMarket!";
                var newPost = new conversations
                {
                    sender = 1,
                    receiver = Convert.ToInt32(userid),
                    message = message,
                    date = DateTime.Now,
                    status = "Por ler"
                };
                db.conversations.Add(newPost);
                db.SaveChanges();

Pages/categorias.cshtml
@page
@model MyApp.Namespace.categoriasModel
@using openmarket.Models;
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@section head{
<title>OpenMarket - Categorias</title>
<meta name="title" content="OpenMarket - Categorias" />
<meta name="description" content="Descubre todas as categorias do OpenMarket" />
@* Facebook, Others *@
<meta property="og:title" content="OpenMarket - Categorias">
<meta property="og:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
<meta property="og:image:width" content="400" />
<meta property="og:image:height" content="300" />
<meta property="og:url" content="https://www.openmarket.com/categorias">
<meta property="og:type" content="article" />
<meta property="og:description" content="Descubre todas as categorias do OpenMarket">
@* Twitter *@
<meta property="twitter:title" content="OpenMarket - Categorias">
<meta name="twitter:description" content="Descubre todas as categorias do OpenMarket">
<meta name="twitter:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://www.openmarket.com/categorias" />
<link rel="stylesheet" href="~/css/adverts.css?v=104" />
}
@section login{
<div class="navbar-login">
    <a class="login-link" href="~/entrar">My OpenMarket</a>
</div>
}
<h3 class="categories-slogan">Encontre anúncios por categorias</h3>
<div class="groups-container">
    <div class="groups-content">
        @foreach (var item in Model.Groups.OrderBy(x => x.name))
        {
            <a href="#@item.name">@item.name</a>
        }
        <div class="adsense">
           
        </div>
    </div>
    <div class="categoriesOptions-content">
        @foreach (var item in Model.Groups.OrderBy(x => x.name))
        {
            valueFormat formatter = new valueFormat();
            string groupName = formatter.encodeText(@item.name);
            <div class="categories-bygroup">
                <a href="anuncios?categoria=@groupName" id="@item.name" class="categories-bygroup groups">@item.name</a>
                <div class="categories-bygroup categories">
                    @foreach (var item2 in Model.Categories.Where(x => x.group_id == item.id).OrderBy(x => x.name))
                    {
                        string categoryName = formatter.encodeText(@item2.name);
                        <a href="~/anuncios?sub_categoria=@categoryName">@item2.name</a>
                    }
                </div>
            </div>
        }
    </div>
</div>
@if (Model.alerts_list != null)
{
    foreach (var alert in Model.alerts_list)
    {
        <div class="alerts-container">
    <div class="alert-content">
        <span onclick="closePanel('alerts-container');cookieAlert('fz_ctg', '@alert.cookie_time');">&times;</span>
        <h2>@alert.title</h2>
        <textarea id="alert-text" readonly>@alert.text</textarea>
        <script>
            var textarea = document.getElementById("alert-text");
            textarea.style.height = textarea.scrollHeight + 20 + "px";
        </script>
        @if (!string.IsNullOrEmpty(@alert.button_text))
                {
                    <a onclick="cookieAlert('fz_ctg', '@alert.cookie_time')" href="@alert.button_url">@alert.button_text</a>
                }
            </div>
        </div>
    }
}

Pages/entrar.cshtml
@page 
@model MyApp.Namespace.entrarModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@section head{
<title>OpenMarket - Entrar</title>
<meta name="title" content="OpenMarket - Entrar" />
<meta name="description" content="Página de inicio de sessão e registo." />
@* Facebook, Others *@
<meta property="og:title" content="OpenMarket - Entrar">
<meta property="og:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
<meta property="og:image:width" content="400" />
<meta property="og:image:height" content="300" />
<meta property="og:url" content="https://www.openmarket.com/entrar">
<meta property="og:type" content="article" />
<meta property="og:description" content="Página de inicio de sessão e registo.">
@* Twitter *@
<meta property="twitter:title" content="OpenMarket - Entrar">
<meta name="twitter:description" content="Página de inicio de sessão e registo.">
<meta name="twitter:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
<meta name="twitter:card" content="summary_large_image">

<link rel="canonical" href="https://www.openmarket.com/entrar/" />
<link rel="stylesheet" href="~/css/login.css?v=104" />
<link rel="stylesheet" href="~/css/loading.css?v=104" />
<script defer src="~/js/main.js?v=104"></script>
<script async src="~/js/social.js?v=104"></script>
}
<div id="alert-message-container" style="display: none;">
    <div class="alert-content">
        <h4 id="message"></h4>
        <button onclick="document.getElementById('alert-message-container').style.display = 'none'">Voltar</button>
    </div>
</div>
<section class="login-container">
    <div class="openmarket-ads login-ads vertical-ads">
        <a href="https://www.openmarket.com">
            <img src="/pubs/anuncios-vertical.jpg" alt="OpenMarket">
        </a>
        <p>OpenMarket Ads</p>
    </div>
    <div class="login-content">
        <div class="login-options">
            <button id="button-login" onclick="login_form()" type="button">Entrar</button>
            <button id="button-register" onclick="register_form()" type="button">Registar</button>
        </div>
        <form method="POST" asp-page-handler="Login" id="login-form" class="login-form">
            <div>
                <label>E-mail</label>
                <input placeholder="E-mail" asp-for="accounts.email" type="email">
            </div>
            <div>
                <label>Password</label>
                <input placeholder="Password" asp-for="accounts.password" type="password">
            </div>
            <a href="/minha-conta/recuperar-password">Recuperar password</a>
            @if (!string.IsNullOrEmpty(Model.backUrl))
            {
                <button value="@Model.backUrl" name="backUrl" type="submit">Efectuar o meu
                    login</button>
            }
            else
            {
                <button name="button_login" type="submit">Efectuar o meu
                    login</button>
            }
            <button onclick="register_form()" type="button">Criar um conta</button>
            <div class="social-content">
                <div onclick="loginfb();" id="facebook-button" class="social-buttons">
                    <img src="/imgs/social/facebook.png" alt="Facebook">
                    <p>Entrar com o Facebook</p>
                </div>

                @* <div onclick="loginGoogle()" class="g-signin2" data-onsuccess="onSignIn"></div> *@
            </div>
            <p>Ao fazer o login está a aceitar os <a href="termos-condicoes">Termos e Condições</a> do OpenMarket.</p>
        </form>
        <form method="POST" asp-page-handler="Facebook" id="facebook-login" class="login-social">
            @if (!string.IsNullOrEmpty(Model.backUrl))
            {
                <button value="@Model.backUrl" name="backUrl" id="facebookButton" type="submit"></button>
            }
            else
            {
                <button name="button_login" id="facebookButton" type="submit"></button>
            }
        </form>
        <form method="POST" asp-page-handler="Google" id="google-login" class="login-social">
        </form>
        <form method="POST" asp-page-handler="Register" id="register-form" class="register-form">
            <div>
                <label>Primeiro e último nome</label>
                <input maxlength="20" asp-for="accounts.username" id="account-username" type="text">
                <span style="display: none;" id="username-alert">O nome de utilizador não pode conter espaços ou
                    caracteres especiais</span>
            </div>
            <div>
                <label>E-mail</label>
                <input asp-for="accounts.email" id="account-email" type="email">
                <span style="display: none;" id="email-alert">Introduza um email válido</span>
            </div>
            <div>
                <label>Password</label>
                <input asp-for="accounts.password" id="account-password" type="password">
            </div>
            <p>Ao clicar em <b>Registar</b> aceito os <a href="termos-condicoes">Termos e Condições</a>.</p>
            <p>Reconheço que o OpenMarket utiliza a minha informação pessoal de acordo com a <a
                    href="privacidade-cookies">Política de Privacidade e Cookies</a>. O OpenMarket utiliza sistemas
                automatizados e parceiros para analisar o meu uso dos serviços e facultar funcionalidades de produto
                relevantes, conteúdo, publicidade visada e baseada nos meus interesses, bem como protecção contra spam,
                malware e utilização não autorizada.</p>
            <div class="login-newsletter">
                <input id="newsletter-check" asp-for="accounts.newsletter" checked type="checkbox">
                <p>Sim, eu quero receber actualizações sobre produtos e serviços, promoções, ofertas especiais,
                    novidades e eventos do OpenMarket, suas afiliadas e parceiros de negócio (e.g. através de newsletters
                    e/ou mensagens SMS).</p>
            </div>
            @if (!string.IsNullOrEmpty(Model.backUrl))
            {
                <button id="register_button" class="loading-button" type="button" value="@Model.backUrl" name="backUrl"
                onclick="validateRegister()"><span class="button-text">Registar</span></button>
            }
            else if (!string.IsNullOrEmpty(Model.convite))
            {
                <button id="register_button" class="loading-button" type="button" value="@Model.convite" name="invite"
                onclick="validateRegister()"><span class="button-text">Registar</span></button>
            }
            else
            {
                <button id="register_button" class="loading-button" type="button" onclick="validateRegister()"><span
                    class="button-text">Registar</span></button>
            }
            <button type="button" onclick="login_form()">Já tenho uma conta</button>
        </form>
    </div>
    <div class="openmarket-ads login-ads vertical-ads">
        <a href="https://www.openmarket.com">
            <img src="/pubs/anuncios-vertical.jpg" alt="OpenMarket">
        </a>
        <p>OpenMarket Ads</p>
    </div>
</section>
<div class="user-footer">
    <h3>Mais informações</h3>
    <a href="~/sobre-nos"><span>Sobre o OpenMarket</span><span>&#10095;</span></a>
    <a href="~/inserir-anuncios"><span>Vender no OpenMarket</span><span>&#10095;</span></a>
    <a href="~/contacte-nos"><span>Contacte-nos</span><span>&#10095;</span></a>
    <a href="~/termos-condicoes"><span>Termos e Condições</span><span>&#10095;</span></a>
    <a href="~/privacidade-cookies"><span>Privacidade e Cookies</span><span>&#10095;</span></a>
    <a href="~/dicas-seguranca"><span>Dicas de Segurança</span><span>&#10095;</span></a>
    <a href="~/categorias"><span>Anúncios por Categorias</span><span>&#10095;</span></a>
    <a href="~/paginas/municipios"><span>Anúncios por Municípios</span><span>&#10095;</span></a>
    <div class="social">
        <h4>Siga-nos</h4>
        <a href="http://www.facebook.com/openmarket"><img src="/imgs/social/facebook.png" alt="Facebook"></a>
        <a href="http://www.instagram.com/openmarket"><img src="/imgs/social/instagram.png" alt="Instagram"></a>
        <a href="http://www.linkedin.com/company/openmarket"><img src="/imgs/social/linkedin.png" alt="LinkedIn"></a>
    </div>
</div>
<div class="div-loading loading-advert">
    <h1>Aguarde um momento, por favor!</h1>
    <h2>Estamos a criar a sua conta.</h2>
    <span class="loading-effect effect-white"></span>
</div>
@if (Model.alerts_list != null)
{
    foreach (var alert in Model.alerts_list)
    {
        <div class="alerts-container">
    <div class="alert-content">
        <span onclick="closePanel('alerts-container');cookieAlert('fz_lg', '@alert.cookie_time');">&times;</span>
        <h2>@alert.title</h2>
        <textarea id="alert-text" readonly>@alert.text</textarea>
        <script>
            var textarea = document.getElementById("alert-text");
            textarea.style.height = textarea.scrollHeight + 20 + "px";
        </script>
        @if (!string.IsNullOrEmpty(@alert.button_text))
                {
                    <a onclick="cookieAlert('fz_lg', '@alert.cookie_time')" href="@alert.button_url">@alert.button_text</a>
                }
            </div>
        </div>
    }
}
@if (Model.register == true)
{
    <script type="text/javascript">
        var login = document.getElementById("login-form");
        var register = document.getElementById("register-form");
        var login_button = document.getElementById("button-login");
        var register_button = document.getElementById("button-register");
        login.style.display = "none";
        register.style.display = "flex";
        login_button.style.borderBottom = "1px solid black";
        register_button.style.borderBottom = "2px solid black";
        login_button.style.fontWeight = "normal";
        register_button.style.fontWeight = "bold";
    </script>
}
@switch (Model._Msg)
{
    case "nao-encontrado":
        <script async type="text/javascript">
    document.getElementById('alert-message-container').style.display = "flex";
    document.getElementById('message').innerHTML = "Email não encontrado!";
</script>
        break;

    case "email-registado":
        <script type="text/javascript">
    document.getElementById('alert-message-container').style.display = "flex";
    document.getElementById('message').innerHTML = "O email inserido já está em uso!";
    register_form();
</script>
        break;
        case "conta-bloqueada":
        <script type="text/javascript">
    document.getElementById('alert-message-container').style.display = "flex";
    document.getElementById('message').innerHTML = "Esta conta encontra-se bloqueada. Para mais informações contacte a nossa equipa.";
</script>
        break;

    case "nome-utilizador-registado":
        <script type="text/javascript">
    document.getElementById('alert-message-container').style.display = "flex";
    document.getElementById('message').innerHTML = "O nome de utilizador inserido já está em uso!";
    register_form();
</script>
        break;

    case "login-incorrecto":
        <script type="text/javascript">
    document.getElementById('alert-message-container').style.display = "flex";
    document.getElementById('message').innerHTML = "Email ou password errado! <br/> Tente novamente.";
</script>
        break;
}