Pages/minha-conta/dados-pessoais.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using openmarket.Models;

namespace MyApp.Namespace
{
    public class dados_pessoaisModel : PageModel
    {
        public AppDbContext db;
        [BindProperty(SupportsGet = true)] public int SessionUser { get; set; } = 0;
        [BindProperty] public byte[] UserPicture { get; set; }
        [BindProperty] public int Cookies { get; set; }
        [BindProperty] public string _Msg { get; set; }
        public IHttpContextAccessor accessor { get; set; }
        [BindProperty] public accounts accounts { get; set; }
        [BindProperty(SupportsGet = true)] public IFormFile uploadImages { get; set; }
        public IList<cities> cities;
        public IList<municipalities> municipalities;
        public IList<alerts> alerts_list;
        public dados_pessoaisModel(AppDbContext _db, IHttpContextAccessor _accessor)
        {
            db = _db;
            accessor = _accessor;
        }
        public IActionResult OnGet(string Msg)
        {
            _Msg = Msg;
            if (Request.Cookies["Accepted"] != null)
            {
                Cookies = 1;
            }
            else
            {
                Cookies = 0;
            }
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userID")))
            {
                SessionUser = Convert.ToInt32(HttpContext.Session.GetString("userID"));
                if (db.accounts.Where(x => x.id == SessionUser).Select(x => x.status).Single() == 11)
                {
                    HttpContext.Session.Remove("userID");
                    if (Request.Cookies["fzid"] != null)
                    {
                        var cookieOptions = new CookieOptions
                        {
                            Expires = DateTime.Now.AddDays(-1)
                        };
                        Response.Cookies.Append("fzid", "0", cookieOptions);
                    }
                    return Redirect("~/entrar");
                }
            }
            else
            {
                valueFormat formatter = new valueFormat();
                string userCookie = Request.Cookies["fzid"];
                if (userCookie != null)
                {
                    int id = Convert.ToInt32(formatter.decrypter(userCookie));
                    if (db.accounts.Where(x => x.id == id).Count() == 1)
                    {
                        SessionUser = id;
                        HttpContext.Session.SetString("userID", Convert.ToString(SessionUser));
                    }
                    else if (!string.IsNullOrEmpty(Request.Query["backUrl"]))
                    {
                        return Redirect("~/entrar?backUrl=" + Request.Query["backUrl"]);
                    }
                    else
                    {
                        return Redirect("~/entrar?");
                    }
                }
                else
                {
                    if (!string.IsNullOrEmpty(Request.Query["backUrl"]))
                    {
                        return Redirect("~/entrar?backUrl=" + Request.Query["backUrl"]);
                    }
                    else
                    {
                        return Redirect("~/entrar?");
                    }
                }
            }
            if (Request.Cookies["fz_dp"] == null)
            {
                alerts_list = db.alerts.Where(x => x.page == "dados-pessoais" && x.status == 1).ToList();
            }
            accounts = db.accounts.First(x => x.id == SessionUser);
            cities = db.cities.OrderBy(x => x.name).ToList();
            if (!string.IsNullOrEmpty(accounts.city))
            {
                int city = db.cities.Where(x => x.name == accounts.city).Select(x => x.id).First();
                municipalities = db.municipalities.Where(x => x.city == city).OrderBy(x => x.name).ToList();
            }
            return null;
        }
        public IActionResult OnGetCategories(string group)
        {
            var group_id = db.groups.Where(x => x.name == group).Select(x => x.id).First();
            var categories = db.categories.Where(x => x.group_id == group_id).OrderBy(x => x.name).Select(x => x.name).ToList();
            return new JsonResult(categories);
        }
        public IActionResult OnGetMunicipalities(string city)
        {
            var city_id = db.cities.Where(x => x.name == city).Select(x => x.id).First();
            var municipalities = db.municipalities.Where(x => x.city == city_id).OrderBy(x => x.name).Select(x => x.name).ToList();
            return new JsonResult(municipalities);
        }
        public IActionResult OnPostData()
        {
            SessionUser = Convert.ToInt32(HttpContext.Session.GetString("userID"));
            var user = db.accounts.First(x => x.id == SessionUser);
            if (uploadImages != null)
            {
                var image = SixLabors.ImageSharp.Image.Load(uploadImages.OpenReadStream());
                int width = 0;
                int height = 0;
                if ((image.Width < 2001 && image.Width > 500) || (image.Height < 2001 && image.Height > 500))
                {
                    width = image.Width / 2;
                    height = image.Height / 2;
                }
                else if (image.Width > 8000 || image.Height > 8000)
                {
                    width = image.Width / 9;
                    height = image.Height / 9;
                }
                else if (image.Width > 7000 || image.Height > 7000)
                {
                    width = image.Width / 8;
                    height = image.Height / 8;
                }
                else if (image.Width > 6000 || image.Height > 6000)
                {
                    width = image.Width / 7;
                    height = image.Height / 7;
                }
                else if (image.Width > 5000 || image.Height > 5000)
                {
                    width = image.Width / 6;
                    height = image.Height / 6;
                }
                else if (image.Width > 4000 || image.Height > 4000)
                {
                    width = image.Width / 5;
                    height = image.Height / 5;
                }
                else if (image.Width > 3000 || image.Height > 3000)
                {
                    width = image.Width / 4;
                    height = image.Height / 4;
                }
                else if (image.Width > 2000 || image.Height > 2000)
                {
                    width = image.Width / 3;
                    height = image.Height / 3;
                }
                image.Mutate(x => x.Resize(width, height));
                MemoryStream ms = new MemoryStream();
                image.SaveAsJpeg(ms);
                user.picture = ms.ToArray();
            }
            user.first_name = accounts.first_name;
            user.last_name = accounts.last_name;
            if (!string.IsNullOrEmpty(accounts.email))
            {
                user.email = accounts.email;
            }
            if (accounts.birthday.ToShortDateString() != "01/01/0001")
            {
                user.birthday = accounts.birthday;
            }
            user.city = accounts.city;
            user.locality = accounts.locality;
            user.municipality = accounts.municipality;
            db.Update(user);
            db.SaveChanges();
            return RedirectToPage("dados-pessoais", new { Msg = "Sucesso" });
        }
        public IActionResult OnPostPassword(string password, string newPassword, string newPasswordR)
        {
            SessionUser = Convert.ToInt32(HttpContext.Session.GetString("userID"));
            string userPassword = db.accounts.Where(x => x.id == SessionUser).Select(x => x.password).First().ToString();
            if (string.IsNullOrEmpty(userPassword) && !string.IsNullOrEmpty(newPassword) && !string.IsNullOrEmpty(newPasswordR))
            {
                var user = db.accounts.First(x => x.id == SessionUser);
                user.password = newPassword;
                db.Update(user);
                db.SaveChanges();
                return RedirectToPage("dados-pessoais", new { Msg = "Sucesso" });
            }
            else if (!string.IsNullOrEmpty(userPassword) && !string.IsNullOrEmpty(password) && !string.IsNullOrEmpty(newPassword) && !string.IsNullOrEmpty(newPasswordR))
            {
                var user = db.accounts.First(x => x.id == SessionUser);
                user.password = newPassword;
                db.Update(user);
                db.SaveChanges();
                return RedirectToPage("dados-pessoais", new { Msg = "Sucesso" });
            }
            else
            {
                return RedirectToPage("dados-pessoais", new { Msg = "Password" });
            }
        }
        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Remove("userID");
            if (Request.Cookies["fzid"] != null)
            {
                var cookieOptions = new CookieOptions
                {
                    Expires = DateTime.Now.AddDays(-1)
                };
                Response.Cookies.Append("fzid", "0", cookieOptions);
            }
            return Redirect("~/index");
        }
    }
}

Pages/minha-conta/recuperar-password.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;
using System.Net.Mail;
using System.IO;
using Microsoft.AspNetCore.Http;
using openmarket.Models;

namespace MyApp.Namespace
{
    public class recuperar_passwordModel : PageModel
    {
        public AppDbContext db;
        public recuperar_passwordModel(AppDbContext _db)
        {
            db = _db;
        }
        [BindProperty] public int Cookies { get; set; }
        [BindProperty] public int SessionUser { get; set; } = 0;
        public string _Msg { get; set; }
        StreamReader reader;
        string body = string.Empty;
        public IList<alerts> alerts_list;
        public void OnGet(string Msg)
        {
            _Msg = Msg;
            if (Request.Cookies["Accepted"] != null)
            {
                Cookies = 1;
            }
            else
            {
                Cookies = 0;
            }
            SessionUser = 0;
            if (Request.Cookies["fzid"] != null)
            {
                var cookieOptions = new CookieOptions
                {
                    Expires = DateTime.Now.AddDays(-1)
                };
                Response.Cookies.Append("fzid", "0", cookieOptions);
            }
            if (Request.Cookies["fz_rp"] == null)
            {
                alerts_list = db.alerts.Where(x => x.page == "recuperar-password" && x.status == 1).ToList();
            }
        }
        public IActionResult OnPostMail(string email)
        {
            var chars = "ABCDEFGHIJKLMNOPQRSTUVXZabcdefghijklmnopqrstuvxz1234567890";
            var stringChars = new char[8];
            var rdm = new Random();
            for (int i = 0; i < stringChars.Length; i++)
            {
                stringChars[i] = chars[rdm.Next(chars.Length)];
            }

            string password = new string(stringChars);

            if (db.accounts.Where(x => x.email == email).FirstOrDefault() != null)
            {
                SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential("openmarket@gmail.com", "YourPassword");
                smtp.EnableSsl = true;
                MailAddress from = new MailAddress("openmarket@gmail.com", "OpenMarket");
                MailAddress to = new MailAddress(email);
                MailMessage mailMessage = new MailMessage(from, to);
                mailMessage.Subject = "OpenMarket - Nova Password";
                mailMessage.IsBodyHtml = true;
                reader = new StreamReader("wwwroot/templates/emails/new-password.htm");
                body = reader.ReadToEnd();
                body = body.Replace("{mail}", email);
                body = body.Replace("{password}", password);
                var userPassword = db.accounts.First(x => x.email == email);
                userPassword.password = password;
                db.Update(userPassword);
                db.SaveChanges();
                mailMessage.Body = body;
                smtp.Send(mailMessage);
                return RedirectToPage("recuperar-password", new { Msg = "Sucesso" });
            }
            else
            {
                return RedirectToPage("recuperar-password", new { Msg = email });
            }
        }
    }
}

Pages/minha-conta/conversas.cshtml
@page
@model MyApp.Namespace.conversasModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@section head{
<title>OpenMarket - Conversas</title>
<meta name="title" content="OpenMarket - Conversas" />
<meta name="description" content="Acede às tuas conversas no OpenMarket." />
@* Facebook, Others *@
<meta property="og:title" content="OpenMarket - Conversas">
<meta property="og:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
<meta property="og:url" content="https://www.openmarket.com/minha-conta/conversas">
<meta property="og:type" content="article" />
<meta property="og:description" content="Acede às tuas conversas no OpenMarket.">
@* Twitter *@
<meta property="twitter:title" content="OpenMarket - Conversas">
<meta name="twitter:description" content="Acede às tuas conversas no OpenMarket.">
<meta name="twitter:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://www.openmarket.com/minha-conta/conversas" />
<link rel="stylesheet" href="~/css/chat.css?v=104" />
<script async src="~/js/main.js?v=104"></script>
<script async src="~/js/chat.js?v=104"></script>
}
@section login{
<div class="navbar-login">
    <a class="login-link" href="~/entrar">My OpenMarket</a>
</div>
}
<div id="chat-container">
    <div id="sidebar-users-chat">
        <div id="user-search">
            <button id="backButton" type="button" onclick="history.back()"><span>&#10094;</span> Voltar</button>
            @* <input type="search" name="user_search">
                <button>Procurar</button> *@
        </div>
        <div id="list-chats">
            <span id="closeList"></span>
            @foreach (var chats in Model.chats)
            {
                if (chats.status == "Lido")
                {
                    <button onclick="sendButton(@chats.sender); posts(@chats.sender);">@chats.sender_username</button>
                }
                else
                {
                    <button onclick="sendButton(@chats.sender); posts(@chats.sender);"
                class="to_read">@chats.sender_username</button>
                }
            }
        </div>
    </div>
    <div id="chat-content">
        <div id="chat-header">
            <button id="chatsButton" type="button" onclick="showChats('closed')">&#10095;</button>
            <div id="chat-info">
            </div>
        </div>
        <div id="chat-posts">

        </div>
        <div id="chat-new-post">
            <div id="new-post"></div>
            <div id="post-extras"></div>
        </div>
    </div>
</div>
<div class="openmarket-ads vertical-ads chat-ads">
    <a href="https://www.openmarket.com">
        <img src="/pubs/anuncios-vertical.jpg" alt="OpenMarket">
    </a>
    <p>OpenMarket Ads</p>
</div>
@if (Model.alerts_list != null)
{
    foreach (var alert in Model.alerts_list)
    {
        <div class="alerts-container">
    <div class="alert-content">
        <span onclick="closePanel('alerts-container');cookieAlert('fz_cht', '@alert.cookie_time');">&times;</span>
        <h2>@alert.title</h2>
        <textarea id="alert-text" readonly>@alert.text</textarea>
        <script>
            var textarea = document.getElementById("alert-text");
            textarea.style.height = textarea.scrollHeight + 20 + "px";
        </script>
        @if (!string.IsNullOrEmpty(@alert.button_text))
                {
                    <a onclick="cookieAlert('fz_cht', '@alert.cookie_time')" href="@alert.button_url">@alert.button_text</a>
                }
            </div>
        </div>
    }
}
<script>
            var chat = document.getElementById("chat-container");
            if(window.outerWidth > 1000)
            {
                chat.setAttribute("style", "height:" + (window.innerHeight - 90) + "px");
            }
            else if(window.outerWidth < 600)
            {
                chat.setAttribute("style", "height:" + (window.innerHeight - 105) + "px");
            }
            else if(window.outerWidth > 601 && window.outerWidth < 1199 && window.outerHeight >= window.outerWidth)
            {
                chat.setAttribute("style", "height:" + (window.innerHeight - 110) + "px");
            }
            else if(window.outerHeight > 600 && window.outerHeight < 1100 && window.outerWidth < 800 && window.outerWidth > window.outerHeight)
            {
                chat.setAttribute("style", "height:" + (window.innerHeight - 135) + "px");
            }
            else if (window.outerHeight > 300 && window.outerHeight < 599 && window.outerHeight < window.outerWidth)
            {
                chat.setAttribute("style", "height:" + (window.innerHeight - 120) + "px");
            }
        </script>

Pages/minha-conta/dados-pessoais.cshtml
@page "{Msg?}"
@model MyApp.Namespace.dados_pessoaisModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@section head{
<title>OpenMarket - Dados Pessoais</title>
<meta name="title" content="OpenMarket - Dados Pessoais" />
<meta name="description"
    content="Atualiza os dados da tua conta." />
@* Facebook, Others *@
<meta property="og:title" content="OpenMarket - Dados Pessoais">
<meta property="og:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
<meta property="og:image:width" content="400" />
<meta property="og:image:height" content="300" />
<meta property="og:url" content="https://www.openmarket.com/minha-conta/dados-pessoais">
<meta property="og:type" content="article" />
<meta property="og:description"
    content="Atualiza os dados da tua conta.">
@* Twitter *@
<meta property="twitter:title" content="OpenMarket - Dados Pessoais">
<meta name="twitter:description"
    content="Atualiza os dados da tua conta.">
<meta name="twitter:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
<meta name="twitter:card" content="summary_large_image">

<link rel="canonical" href="https://www.openmarket.com/minha-conta/dados-pessoais" />
<link rel="stylesheet" href="~/css/account.css?v=104" />
<script async src="~/js/main.js?v=104"></script>
}
@section login{
<div class="navbar-login">
    <a class="login-link" href="~/entrar">My OpenMarket</a>
</div>
}
<div id="menu-container">
    <partial name="_UserMenu"/>
    <div class="openmarket-ads ads-menu vertical-ads"></div>
</div>
<div id="alert-message-container" style="display: none;">
    <div class="alert-content">
        <h3 id="alert-message-title">Dados gravados com sucesso</h3>
        <button type="button" id="button_return"
            onclick="document.getElementById('alert-message-container').style.display = 'none'">Voltar</button>
    </div>
</div>
<div class="personal-info-container">
    <form form method="post" class="personal-info" enctype="multipart/form-data">
        <h3>Alterar dados</h3>
        @{
            <input type="file" name="uploadImages" id="image" accept="image/jpg, image/jpeg"
                style="display: none;" onchange="PreviewImage('image')">
            var imgSrc = string.Empty;
            byte[] byteImage = Model.accounts.picture;
            if (byteImage != null)
            {
                var base64 = Convert.ToBase64String(byteImage);
                imgSrc = String.Format("data:image/gif;base64,{0}", base64);
            }
            else
            {
                imgSrc = "/imgs/WithoutPicture.jpg";
            }
            <div class="account-info">
                <div>
                    <img title="Alterar imagem" alt="Imagem do artigo" src="@imgSrc" id="button_image"
                        onclick="document.getElementById('image').click();">
                </div>
                <div class="account-name">
                    <input placeholder="Nome" class="input-style" id="account-first-name" type="text"
                    asp-for="accounts.first_name">
                    <input placeholder="Apelido" class="input-style" id="account-last-name" type="text"
                    asp-for="accounts.last_name">
                    @if (!string.IsNullOrEmpty(Model.accounts.facebook_id.ToString()))
                    {
                        <input placeholder="Email" class="input-style" id="account-email" type="text" asp-for="accounts.email">
                    }
                </div>
            </div>

        }
        <label class="account-label label-location">Localização</label>
        <div class="account-location">
            <div>
                <select class="select-style" onchange="loadMunicipalities('anunciar-vender', '')"
                    asp-for="accounts.city" id="cities-selector">
                    <option value="">Província</option>
                    @foreach (var item in Model.cities)
                    {
                        <option value="@item.name">@item.name</option>
                    }
                </select>
            </div>
            @if (Model.municipalities != null)
            {
                <div id="municipality-content" class="municipality-content">
                    <select asp-for="accounts.municipality" class="municipality-selector select-style"
                    id="municipality-selector">
                        @foreach (var item in Model.municipalities)
                        {
                            if (Model.accounts.municipality == item.name)
                            {
                                <option selected value="@item.name">@item.name</option>
                            }
                            else
                            {
                                <option value="@item.name">@item.name</option>
                            }
                        }
                    </select>
                </div>
                <div id="locality-content">
                    <input asp-for="accounts.locality" id="account-locality" type="text" class="input-style"
                    placeholder="Localidade">
                </div>
            }
            else
            {
                <div id="municipality-content" class="municipality-content">
                    <select asp-for="accounts.municipality" class="municipality-selector select-style"
                    id="municipality-selector">
                        <option value="">Município</option>
                    </select>
                </div>
                <div id="locality-content">
                    <input asp-for="accounts.locality" id="account-locality" type="text" class="input-style"
                    placeholder="Localidade">
                </div>
            }
        </div>
        <span id="location-account-alert" class="account-alert"></span>
        <div id="birthday-button">
            <div>
                <label class="account-label label-birthday">Data de nascimento</label>
                @if (Model.accounts.birthday.ToShortDateString() == "01/01/0001")
                {
                    <input class="input-style" id="account-birthday" type="date" asp-for="accounts.birthday">
                    <script type="text/javascript">
                        document.getElementById("account-birthday").defaultValue = "2000-01-01";
                    </script>
                }
                else
                {
                    <input class="input-style" id="account-birthday" type="date" asp-for="accounts.birthday">
                }
            </div>
            <button type="submit" asp-page-handler="Data">Guardar</button>
        </div>
    </form>
    <form asp-page-handler="Password" method="post" id="changePassword" class="change-password">
        <h3>Alterar password</h3>
        @if (!string.IsNullOrEmpty(Model.accounts.password))
        {
            <input placeholder="Password actual" class="input-style user-password" type="password" name="password"
            id="user-password">
        }
        <input placeholder="Nova password" class="input-style user-password" type="password" name="newPassword"
            id="user-new-password">
        <input placeholder="Repita a password" class="input-style user-password" type="password" name="newPasswordR"
            id="user-new-r-password">
        <button onclick="validPassword()" type="button">Alterar</button>
    </form>
</div>
@if (Model.alerts_list != null)
{
    foreach (var alert in Model.alerts_list)
    {
        <div class="alerts-container">
    <div class="alert-content">
        <span onclick="closePanel('alerts-container');cookieAlert('fz_dp', '@alert.cookie_time');">&times;</span>
        <h2>@alert.title</h2>
        <textarea id="alert-text" readonly>@alert.text</textarea>
        <script>
            var textarea = document.getElementById("alert-text");
            textarea.style.height = textarea.scrollHeight + 20 + "px";
        </script>
        @if (!string.IsNullOrEmpty(@alert.button_text))
                {
                    <a onclick="cookieAlert('fz_dp', '@alert.cookie_time')" href="@alert.button_url">@alert.button_text</a>
                }
            </div>
        </div>
    }
}
@if (Model._Msg == "Sucesso")
{
    <script type="text/javascript">
    document.getElementById("alert-message-container").style.display = "flex";
</script>
}
else if (Model._Msg == "Password")
{
    <script type="text/javascript">
    var password = document.getElementById("user-password");
    var new_password = document.getElementById("user-new-password");
    var new_r_password = document.getElementById("user-new-r-password");
    document.getElementById("alert-message-container").style.display = "flex";
    password.style.backgroundColor = "rgb(31, 140, 212, 0.3)";
    new_password.style.backgroundColor = "rgb(31, 140, 212, 0.3)";
    new_r_password.style.backgroundColor = "rgb(31, 140, 212, 0.3)";
    document.getElementById("alert-message-title").innerHTML = "Os campos tem que estar todos preenchidos!";
</script>
}

Pages/minha-conta/recuperar-password.cshtml
@page "{Msg?}"
@model MyApp.Namespace.recuperar_passwordModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@section head{
<title>OpenMarket - Recuperar Password</title>
<meta name="title" content="OpenMarket - Recuperar Password" />
<meta name="description" content="Recupera a password da tua conta de forma rápida e segura." />
@* Facebook, Others *@
<meta property="og:title" content="OpenMarket - Recuperar Password">
<meta property="og:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
<meta property="og:image:width" content="400" />
<meta property="og:image:height" content="300" />
<meta property="og:url" content="https://www.openmarket.com/minha-conta/recuperar-password">
<meta property="og:type" content="article" />
<meta property="og:description" content="Recupera a password da tua conta de forma rápida e segura.">
@* Twitter *@
<meta property="twitter:title" content="OpenMarket - Recuperar Password">
<meta name="twitter:description" content="Recupera a password da tua conta de forma rápida e segura.">
<meta name="twitter:image" content="https://www.openmarket.com/imgs/Logotipo.jpg">
<meta name="twitter:card" content="summary_large_image">

<link rel="canonical" href="https://www.openmarket.com/minha-conta/recuperar-password" />
<link rel="stylesheet" href="~/css/account.css?v=104" />
<script async src="~/js/main.js?v=104"></script>
}
@section login{
<div class="navbar-login">
    <a href="~/entrar">My OpenMarket</a>
</div>
}
<div class="instructions-panel" id="alert-message-container" style="display: none;">
    <div class="alert-content">
        <h2>Instruções</h2>
        <p>1º Abra o email enviado</p>
        <p>2º Veja qual o nova senha definida para si</p>
        <p>3º Entre em <a href="www.openmarket.com/entrar">OpenMarket.com - Entrar</a> e coloque o seu email e a
            nova senha</p>
        <p>Nota: Recomendamos que troque a senha por uma nova à sua escolha</p>
        <a href="~/entrar">Iniciar Sessão</a>
    </div>
</div>
<div class="recover-password-container">
    <div class="recover-content">
        <h2>Esqueceu a sua senha?</h2>
        <form method="POST" asp-page-handler="Mail" id="form-recover-password" class="passwordRecover-content">
            <p>Endereço de e-mail</p>
            <div>
                <input type="email" name="email" id="email" placeholder="E-mail">
                <button type="button"
                    onclick="emailValidation('email','form-recover-password', 'recover-password-alert')"
                    class="password-button">Recuperar</button>
            </div>
            <span id="recover-password-alert"></span>
        </form>
    </div>
</div>
@if (Model.alerts_list != null)
{
    foreach (var alert in Model.alerts_list)
    {
        <div class="alerts-container">
    <div class="alert-content">
        <span onclick="closePanel('alerts-container');cookieAlert('fz_rp', '@alert.cookie_time');">&times;</span>
        <h2>@alert.title</h2>
        <textarea id="alert-text" readonly>@alert.text</textarea>
        <script>
            var textarea = document.getElementById("alert-text");
            textarea.style.height = textarea.scrollHeight + 20 + "px";
        </script>
        @if (!string.IsNullOrEmpty(@alert.button_text))
                {
                    <a onclick="cookieAlert('fz_rp', '@alert.cookie_time')" href="@alert.button_url">@alert.button_text</a>
                }
            </div>
        </div>
    }
}
@if (Model._Msg == "Sucesso")
{
    <script type="text/javascript">
    var panel = document.querySelector(".instructions-panel");
    panel.style.display = "flex";
</script>
}
else if (Model._Msg != null)
{
    <script type="text/javascript">
    document.getElementById("email").innerHTML == @Model._Msg;
    document.getElementById("recover-password-alert").innerHTML == "Este email não está registado!";
</script>
}